#!/usr/bin/env python
"""Emit the SYNTHETIC cognition corpus fixture as JSONL (Step 5c harness).

THIS WRITES A SYNTHETIC FIXTURE, NOT A REAL CORPUS. See
``cognition_wobble.calibration.synthetic`` for the loud caveat: every
row is machine-generated to exercise the load -> train -> eval pipeline,
not to train a shippable classifier.

Usage::

    python scripts/gen_synthetic_cognition_corpus.py \
        --out tests/cognition/fixtures/synthetic_corpus.jsonl

The committed fixture under ``tests/cognition/fixtures/`` is the output
of this script with default arguments; regenerate it here if the schema
or generator changes.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Bootstrap: make phoenix.* and the vendored cognition_wobble.* importable
# regardless of cwd / install mode (mirrors phoenix/__init__'s vendor path
# injection so `python scripts/...` works from a fresh checkout).
_REPO_ROOT = Path(__file__).resolve().parent.parent
for _p in (str(_REPO_ROOT), str(_REPO_ROOT / "vendor")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from cognition_wobble.calibration.synthetic import generate_synthetic_corpus  # noqa: E402
from cognition_wobble.corpus import count_by_class, example_to_record  # noqa: E402

_DEFAULT_OUT = _REPO_ROOT / "tests" / "cognition" / "fixtures" / "synthetic_corpus.jsonl"

_HEADER_LINES = (
    "# SYNTHETIC cognition corpus fixture -- NOT a real labeled corpus.",
    "# Machine-generated by scripts/gen_synthetic_cognition_corpus.py to",
    "# exercise the Step 5c load->train->eval harness end-to-end. Do NOT",
    "# train a shippable classifier on this file. See",
    "# cognition_wobble/calibration/synthetic.py for the design notes.",
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=_DEFAULT_OUT,
        help=f"output JSONL path (default: {_DEFAULT_OUT})",
    )
    parser.add_argument(
        "--n-per-class", type=int, default=40, help="examples per graded class (default: 40)"
    )
    parser.add_argument(
        "--n-unclassified", type=int, default=12, help="gold-UNCLASSIFIED rows (default: 12)"
    )
    parser.add_argument("--seed", type=int, default=1337)
    args = parser.parse_args(argv)

    examples = generate_synthetic_corpus(
        n_per_class=args.n_per_class,
        n_unclassified=args.n_unclassified,
        seed=args.seed,
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8", newline="\n") as fh:
        for line in _HEADER_LINES:
            fh.write(line + "\n")
        for ex in examples:
            rec = example_to_record(ex)
            fh.write(json.dumps(rec, ensure_ascii=False, sort_keys=True) + "\n")

    counts = count_by_class(examples)
    print(f"wrote {len(examples)} examples -> {args.out}")
    for cls, n in counts.items():
        if n:
            print(f"  {cls.value:<26} {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
